force-app/main/default/objects/AWS__c/AWS__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>AWS Integration Settings</label>
</CustomObject>

force-app/main/default/objects/AWS__c/fields/AWS_Record_Type_ID__c.field-meta.xml
<CustomField>
    <fullName>AWS_Record_Type_ID__c</fullName>
    <description>ID for the record AWS opportunity record type</description>
    <label>AWS Record Type ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AWS__c/fields/Is_CMZ__c.field-meta.xml
<CustomField>
    <fullName>Is_CMZ__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is_CMZ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AWS__c/fields/spmsId__c.field-meta.xml
<CustomField>
    <fullName>spmsId__c</fullName>
    <label>spmsId</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Acceptance_Status__c.field-meta.xml
<CustomField>
    <fullName>Acceptance_Status__c</fullName>
    <label>Partner Acceptance Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/APN_CRM_Unique_Identifier__c.field-meta.xml
<CustomField>
    <fullName>APN_CRM_Unique_Identifier__c</fullName>
    <label>APN CRM Unique Identifier</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AWS_Campaign__c.field-meta.xml
<CustomField>
    <fullName>AWS_Campaign__c</fullName>
    <label>AWS Campaign (Additional Comments)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AWS_Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>AWS_Opportunity_Name__c</fullName>
    <label>AWS Opportunity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AWS_Sub_Use_Case__c.field-meta.xml
<CustomField>
    <fullName>AWS_Sub_Use_Case__c</fullName>
    <label>AWS Sub Use Case</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Computer Vision - Video Analysis, OCR, Medical Imaging, Face Detection, etc…</fullName>
            </value>
            <value>
                <fullName>Natural Language Understanding = Sentiment Analysis. Topic modeling, Entity Recognition, Language recognition, etc..</fullName>
            </value>
            <value>
                <fullName>Language Translation</fullName>
            </value>
            <value>
                <fullName>Text to speed, speed to text</fullName>
            </value>
            <value>
                <fullName>Recommendations</fullName>
            </value>
            <value>
                <fullName>Forecasting - time series analysis, demand, etc..</fullName>
            </value>
            <value>
                <fullName>Personalization</fullName>
            </value>
            <value>
                <fullName>Conversational Interfaces</fullName>
            </value>
            <value>
                <fullName>Fraud and ANomaly Detection</fullName>
            </value>
            <value>
                <fullName>Big data analytics &amp; data science</fullName>
            </value>
            <value>
                <fullName>Business Intelligence &amp; data vi</fullName>
            </value>
            <value>
                <fullName>Data integration &amp; ETL</fullName>
            </value>
            <value>
                <fullName>Data Warehouse</fullName>
            </value>
            <value>
                <fullName>Real-time Analytics</fullName>
            </value>
            <value>
                <fullName>Data Lake</fullName>
            </value>
            <value>
                <fullName>Microsoft Apps</fullName>
            </value>
            <value>
                <fullName>Oracle Production</fullName>
            </value>
            <value>
                <fullName>Oracle Non-Prod</fullName>
            </value>
            <value>
                <fullName>SAP Production</fullName>
            </value>
            <value>
                <fullName>SAP Non-Prod</fullName>
            </value>
            <value>
                <fullName>Mainframe Modernization</fullName>
            </value>
            <value>
                <fullName>Contact Center</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Continuous Integration &amp; Continuous Delivery (CICD)</fullName>
            </value>
            <value>
                <fullName>Monitoring, logging and performance</fullName>
            </value>
            <value>
                <fullName>Infrastructure as code</fullName>
            </value>
            <value>
                <fullName>Productivity Applications</fullName>
            </value>
            <value>
                <fullName>AWS Lambda</fullName>
            </value>
            <value>
                <fullName>Kubernetes</fullName>
            </value>
            <value>
                <fullName>OpenShift</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AWS_Use_Case__c.field-meta.xml
<CustomField>
    <fullName>AWS_Use_Case__c</fullName>
    <label>AWS Use Case</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AI/Machine Learning</fullName>
            </value>
            <value>
                <fullName>Big Data</fullName>
            </value>
            <value>
                <fullName>Business Applications</fullName>
            </value>
            <value>
                <fullName>Cloud Management Tools &amp; DevOps</fullName>
            </value>
            <value>
                <fullName>Tools &amp; DevOps</fullName>
            </value>
            <value>
                <fullName>Containers &amp; Serverless</fullName>
            </value>
            <value>
                <fullName>End User Computing</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>Healthcare &amp; Life Sciences</fullName>
            </value>
            <value>
                <fullName>Hybrid Application Platform</fullName>
            </value>
            <value>
                <fullName>Industrial Software</fullName>
            </value>
            <value>
                <fullName>IOT</fullName>
            </value>
            <value>
                <fullName>Media &amp; High Performance Computing (HPC)</fullName>
            </value>
            <value>
                <fullName>Migration</fullName>
            </value>
            <value>
                <fullName>Networking</fullName>
            </value>
            <value>
                <fullName>Security</fullName>
            </value>
            <value>
                <fullName>Storage</fullName>
            </value>
            <value>
                <fullName>AI</fullName>
            </value>
            <value>
                <fullName>Data Residency</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Contract_Vehicle__c</fullName>
    <label>Contract Vehicle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_AWS_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Customer_AWS_Account_Id__c</fullName>
    <label>Customer AWS Account Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Delivery_Model__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Model__c</fullName>
    <label>Delivery Model</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SaaS or PaaS</fullName>
            </value>
            <value>
                <fullName>BYOL or AMI</fullName>
            </value>
            <value>
                <fullName>Managed Services</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>Resell</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Expected_Monthly_AWS_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Expected_Monthly_AWS_Revenue__c</fullName>
    <inlineHelpText>Influenced Revenue equates to the Estimated Monthly Recurring Revenue</inlineHelpText>
    <label>Expected Monthly AWS Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/First_Shared_with_AWS__c.field-meta.xml
<CustomField>
    <fullName>First_Shared_with_AWS__c</fullName>
    <label>First Shared with AWS</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_this_Marketplace__c.field-meta.xml
<CustomField>
    <fullName>Is_this_Marketplace__c</fullName>
    <label>Is this Marketplace?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Marketing_Development_Funded__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Development_Funded__c</fullName>
    <label>Marketing Development Funded?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Partner_Primary_Need__c.field-meta.xml
<CustomField>
    <fullName>Partner_Primary_Need__c</fullName>
    <label>Partner Primary Need</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Architectural validation</fullName>
            </value>
            <value>
                <fullName>Business presentation</fullName>
            </value>
            <value>
                <fullName>Competitive Information</fullName>
            </value>
            <value>
                <fullName>Pricing Assistance</fullName>
            </value>
            <value>
                <fullName>Technical consultation</fullName>
            </value>
            <value>
                <fullName>Total Cost of Ownership Evaluation</fullName>
            </value>
            <value>
                <fullName>For Visibility - No Assistance Needed</fullName>
            </value>
            <value>
                <fullName>Deal support</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Description__c.field-meta.xml
<CustomField>
    <fullName>Project_Description__c</fullName>
    <inlineHelpText>For AWS professional services opportunities, Please answer the following questions: What is the customer looking to do on AWS? What is our role in this project? What are the software applications and tools used to support the solution?</inlineHelpText>
    <label>Project Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Send_to_AWS__c.field-meta.xml
<CustomField>
    <fullName>Send_to_AWS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send to AWS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AceUpdateBatchV2.cls
public with sharing class AceUpdateBatchV2 implements Database.Batchable<SObject>, Database.Stateful, Database.AllowsCallouts, Schedulable {
    private final String QUERY = 'SELECT id, APN_CRM_Unique_Identifier__c, AWS_Use_Case__c, CloseDate, Project_Description__c, Account.BillingPostalCode, name, Owner.Email, Owner.FirstName, Owner.LastName, Owner.Phone, stageName, Industry__c, Account.Website, Account.Name, Account.BillingCountry, Account.BillingState, Partner_Primary_Need__c, Contract_Vehicle__c, Reasons_for_loosing__c, Expected_Monthly_AWS_Revenue__c, Delivery_Model__c, Primary_Contact__r.Phone, Primary_Contact__r.FirstName, Primary_Contact__r.LastName, Primary_Contact__r.Email, Primary_Contact__r.Salutation, Acceptance_status__c, NextStep, Customer_AWS_Account_Id__c, AWS_Campaign__c, Send_to_AWS__c, AWS_Opportunity_Name__c, First_Shared_with_AWS__c, AWS_Sub_Use_Case__c, AWS_Campaign_Name__c, Is_this_Marketplace__c, Marketing_Development_Funded__c FROM Opportunity WHERE recordTypeId =: recordType AND SystemModStamp >= LAST_N_DAYS:1 AND LastModifiedById !=: integrationUser AND Send_to_AWS__c =: CMZBatch';  
    private Integer settingsIndex = 0;
    private AWS__c settings;
    private String recordType;
    private String integrationUser;
    private Boolean CMZBatch;
    private String spmsId;
    private List<Opportunity> firstShared = new List<Opportunity>();
    private List<ID> firstSharedIDs = new List<ID>();
    
    public AceUpdateBatchV2() {
        settings = AceHelperMethodsV2.CheckIntegrationType(settingsIndex);
        recordType = settings.AWS_Record_Type_ID__c;
        CMZBatch = settings.Is_CMZ__c;
        spmsId = settings.spmsID__c; 
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC) { 
        return Database.getQueryLocator(QUERY);
    }
    
    public void execute(SchedulableContext SC) {
        database.executebatch(new AceUpdateBatchV2());
    }
    
    public void execute(Database.BatchableContext BC, List<Opportunity> scope) {
        List<OpportunityJSON> JSONScope = new List<OpportunityJSON>();
        
        for(Opportunity opp : scope){
            if(AceHelperMethodsV2.CheckFirstShared(opp)){ 
                opp.First_Shared_with_AWS__c = Date.Today();
                firstShared.add(opp);          
                //firstSharedIDs.add(opp.id);    
            }            
            JSONScope.add(AceHelperMethodsV2.PrepareJSONRequest(opp));
        }
        
        String resultPath = AceHelperMethodsV2.PutCRUpdateCallout(settings,JSONScope);
        
        if(!Test.isRunningTest()){
            system.enqueueJob(new AceIntegrationFutureQueue(resultPath,settings,0));
        }
    }
    
    public void finish(Database.BatchableContext BC) {
        settingsIndex++;
        if(settingsIndex <=1){
            settings = AceHelperMethodsV2.CheckIntegrationType(settingsIndex);
            recordType = settings.AWS_Record_Type_ID__c;
            CMZBatch = settings.Is_CMZ__c;
            spmsId = settings.spmsID__c;                        
            Database.executeBatch(this);
        }
        else{
            // = [SELECT id, First_Shared_with_AWS__c FROM Opportunity WHERE id IN: firstSharedIDs FOR UPDATE];
            //for(Opportunity o : firstshared){
            //    o.First_Shared_with_AWS__c = Date.Today();
            //}
            Update firstShared;
        }
    }
}