force-app/main/default/objects/AWS__c/AWS__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>AWS Integration Settings</label>
</CustomObject>

force-app/main/default/objects/AWS__c/fields/AWS_Integration_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>AWS_Integration_Account_ID__c</fullName>
    <description>For new opportunities generated by AWS, there needs to be a placeholder account to associate the record to. This field holds the id of the placeholder account</description>
    <label>AWS Integration Account ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AWS__c/fields/AWS_Record_Type_ID__c.field-meta.xml
<CustomField>
    <fullName>AWS_Record_Type_ID__c</fullName>
    <description>ID for the record AWS opportunity record type</description>
    <label>AWS Record Type ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AWS__c/fields/Integration_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Integration_User_Id__c</fullName>
    <label>Integration User Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/APN_CRM_Unique_Identifier__c.field-meta.xml
<CustomField>
    <fullName>APN_CRM_Unique_Identifier__c</fullName>
    <label>APN CRM Unique Identifier</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AWS_Use_Case__c.field-meta.xml
<CustomField>
    <fullName>AWS_Use_Case__c</fullName>
    <label>AWS Use Case</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AI/Machine Learning</fullName>
            </value>
            <value>
                <fullName>Big Data</fullName>
            </value>
            <value>
                <fullName>Business Applications</fullName>
            </value>
            <value>
                <fullName>Cloud Management Tools &amp; DevOps</fullName>
            </value>
            <value>
                <fullName>Tools &amp; DevOps</fullName>
            </value>
            <value>
                <fullName>Containers &amp; Serverless</fullName>
            </value>
            <value>
                <fullName>End User Computing</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>Healthcare &amp; Life Sciences</fullName>
            </value>
            <value>
                <fullName>Hybrid Application Platform</fullName>
            </value>
            <value>
                <fullName>Industrial Software</fullName>
            </value>
            <value>
                <fullName>IOT</fullName>
            </value>
            <value>
                <fullName>Media &amp; High Performance Computing (HPC)</fullName>
            </value>
            <value>
                <fullName>Migration</fullName>
            </value>
            <value>
                <fullName>Networking</fullName>
            </value>
            <value>
                <fullName>Security</fullName>
            </value>
            <value>
                <fullName>Storage</fullName>
            </value>
            <value>
                <fullName>AI</fullName>
            </value>
            <value>
                <fullName>Data Residency</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Delivery_Model__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Model__c</fullName>
    <label>Delivery Model</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SaaS or PaaS</fullName>
            </value>
            <value>
                <fullName>BYOL or AMI</fullName>
            </value>
            <value>
                <fullName>Managed Services</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>Resell</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Expected_Monthly_AWS_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Expected_Monthly_AWS_Revenue__c</fullName>
    <inlineHelpText>Influenced Revenue equates to the Estimated Monthly Recurring Revenue</inlineHelpText>
    <label>Expected Monthly AWS Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Partner_Primary_Need__c.field-meta.xml
<CustomField>
    <fullName>Partner_Primary_Need__c</fullName>
    <label>Partner Primary Need</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Architectural validation</fullName>
            </value>
            <value>
                <fullName>Business presentation</fullName>
            </value>
            <value>
                <fullName>Competitive Information</fullName>
            </value>
            <value>
                <fullName>Pricing Assistance</fullName>
            </value>
            <value>
                <fullName>Technical consultation</fullName>
            </value>
            <value>
                <fullName>Total Cost of Ownership Evaluation</fullName>
            </value>
            <value>
                <fullName>For Visibility - No Assistance Needed</fullName>
            </value>
            <value>
                <fullName>Deal support</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Description__c.field-meta.xml
<CustomField>
    <fullName>Project_Description__c</fullName>
    <inlineHelpText>For AWS professional services opportunities, Please answer the following questions: What is the customer looking to do on AWS? What is our role in this project? What are the software applications and tools used to support the solution?</inlineHelpText>
    <label>Project Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AceUpdateBatchTest.cls
@isTest
public class AceUpdateBatchTest{
    
    @isTest(SeeAllData=true)
    public static void testBatch() {
    
        AWS__c settings = AWS__c.getValues('AWS Integration Settings');
        Date closeDate = System.today();
       
        Test.StartTest();
        Opportunity testOpp = new Opportunity(Name='Test',APN_CRM_Unique_Identifier__c='O7365934',AWS_Use_Case__c='Business Applications',OwnerId=settings.Integration_User_Id__c, RecordTypeId=settings.AWS_Record_Type_ID__c,AccountId=settings.AWS_Integration_Account_ID__c,closeDate=closeDate,stageName='Prospect',Project_Description__c='test',Industry__c='Financial Services',Delivery_Model__c='SaaS or PaaS',Partner_Primary_Need__c='Architectural validation',Expected_Monthly_AWS_Revenue__c=100);  
        Insert testOpp;       
        AceUpdateBatch ace = new AceUpdateBatch();
        database.executebatch(ace);
        Test.StopTest();
        
    }
    
}